### ISSUE TITLE
Can't find CoreLibraries

### ISSUE THREAD

**Issue by R-033** [NFSTools/VaultLib#14]
It doesn't seem like CoreLibraries is included in this repo, but it's referenced in code. Is this intentional?

Great job though, keep it up man

**Comment by LeoCodes21** [comment]
It is not unintentional but it is not exactly intentional either. CoreLibraries will be made public later.

**Comment by LeoCodes21** [comment]
All packages can now be installed through NuGet. Documentation will be added over time.
